Introduce Windows CI, but fixed
AdRoll/rebar3_format pull request #268
Opened 2021-06-10 16:02 UTC by ElectronicRU

Fixes bugs uncovered by #267.

List of changes:
- Common utility file for initializing the state and discovering test app
- Fix git flags in test_app_SUITE
- Made output_dir test in sr_formatter_SUITE able to accept a path with a drive letter in it.

2021-06-10 16:25 UTC, ElectronicRU commented
@paulo-ferraz-oliveira @elbrujohalcon could you take a look? CI fails with some stuff that's non-reproducible to me - it seems like it's improper stup/default, I'm not sure what to make of it.

2021-06-11 09:35 UTC, elbrujohalcon requested changes
Nit-picking 🙈

2021-06-11 09:35 UTC, elbrujohalcon commented on test/test_util.erl
> +-module(test_util).
In NextRoll, we usually call modules like this one `test_utils` (plural).
Sorry about this… but… do you mind changing its name?

2021-06-11 09:35 UTC, elbrujohalcon commented
Now, for that CI pipeline… this is what the error in `git diff` is saying…

```diff
diff --git a/after/src/macros_in_specs.erl b/formatted/src/macros_in_specs.erl
index d8baa3b..98dddb4 100644
--- a/after/src/macros_in_specs.erl
+++ b/formatted/src/macros_in_specs.erl
@@ -17,7 +17,6 @@ g() ->

 %% @doc Can't be parsed
 -spec a_module : ?FOO( ) -> t( ) .
-
 foo() ->
     t.

diff --git a/after/src/others.erl b/formatted/src/others.erl
index 5a7844e..b095c25 100644
--- a/after/src/others.erl
+++ b/formatted/src/others.erl
@@ -77,7 +77,7 @@ try_expr_after() ->
         room ->
             {my, friend}
     catch
-        {you_cant, Open} when Open ->
+        throw:{you_cant, Open} when Open ->
             it:was(Open)
     after
         close:the(door, anyway)
diff --git a/after/src/otp_samples/macros.erl b/formatted/src/otp_samples/macros.erl
index 4e51fd5..7b8411a 100644
--- a/after/src/otp_samples/macros.erl
+++ b/formatted/src/otp_samples/macros.erl
@@ -34,10 +34,8 @@ another_hidden_function() ->
 -define(NO_PARENS, no_parens).

 other_function( ?NO_ARGS( ) , ?NO_PARENS , ?WITH_ARGS( X ) , ?WITH_ARGS( ?WITH_ARGS( ?NO_ARGS( ) ) ) ) -> { ?NO_ARGS( ) , ?NO_PARENS , X } .
-
 %% Careful with parentheses
 -define(Now(), 100).

 -define( Elapsed( Since ) , ( ?Now( ) - Since ) ) .
-
 -define( Remains( Since , Remaining ) , N - ?Elapsed( Since ) ) .
diff --git a/after/src/strings/truncate_strings.erl b/formatted/src/strings/truncate_strings.erl
index bc2e7c7..f075b19 100644
--- a/after/src/strings/truncate_strings.erl
+++ b/formatted/src/strings/truncate_strings.erl
@@ -57,13 +57,13 @@ with_newlines() ->



\n"
+    "





-\n"
-    "



@@ -77,8 +77,9 @@ with_newlines() ->



-    the\npaper\nlimit\nthe\nquick\nbrown\nfox\njumps\n"
-    "    over\nthe\nlazy\ndog,\nyou\nsee".
+    the\npaper\nlimit\nthe\nqu"
+    "ick\nbrown\nfox\njumps
+    over\nthe\nlazy\ndog,\nyou\nsee".

 with_escaped_chars() ->
     "a \\tvery \\tvery \\tvery \\tlong \\tline \\tthat \\tgoes \\tover "
```

2021-06-11 09:58 UTC, elbrujohalcon commented
It might be the `erl_syntax` version…
It seems like, for Windows, the parser sees a [`class_qualifier`](http://erlang.org/doc/man/erl_syntax.html#class_qualifier-3) in `{you_cant, Open} when Open ->`. While, in Linux, it parses it just as a tuple.
No idea how that happens.

2021-06-11 09:59 UTC, elbrujohalcon commented
Also no idea what's the deal with `a.broken.file`… maybe it's adding (or subtracting) a newline at the end of it?

2021-06-11 10:07 UTC, ElectronicRU commented
> It might be the `erl_syntax` version…
> It seems like, for Windows, the parser sees a [`class_qualifier`](http://erlang.org/doc/man/erl_syntax.html#class_qualifier-3) in `{you_cant, Open} when Open ->`. While, in Linux, it parses it just as a tuple.
> No idea how that happens.

I have to imagine that whatever vsn gets installed by gleam is wrong... the escript references "erl10.0" - is that right?

2021-06-11 10:31 UTC, elbrujohalcon commented
> I have to imagine that whatever vsn gets installed by gleam is wrong... the escript references "erl10.0" - is that right?

No idea. @paulo-ferraz-oliveira do you know?

2021-06-14 10:07 UTC, paulo-ferraz-oliveira commented
> > I have to imagine that whatever vsn gets installed by gleam is wrong... the escript references "erl10.0" - is that right?
> 
> No idea. @paulo-ferraz-oliveira do you know?

Let me check.

2021-06-14 10:18 UTC, paulo-ferraz-oliveira commented
So, https://github.com/gleam-lang/setup-erlang/blob/main/main.ps1#L4 seems to convert 21.3 to 21. We might just have to open an issue next to `setup-erlang`. Let me do that.

2021-06-14 12:02 UTC, ElectronicRU commented
Would it be acceptable to bump gleam's version to 22 for now?

2021-06-14 13:18 UTC, paulo-ferraz-oliveira commented
I'm pretty sure 22 has no pre-compiled Windows versions (on the Erlang Solutions repo.), which is why I chose 21.3, but you can always try **again**, here, and we can BE sure 🤣 (I looked around and couldn't find a reference to where I state 22 isn't available - since I trust past-me).

2021-07-08 11:19 UTC, paulo-ferraz-oliveira commented
@ElectronicRU, any news on this? I'd like to test an update to the Windows CI, but would prefer to do it on an already working version 😄 Thanks.

2021-07-11 23:13 UTC, ElectronicRU commented
@paulo-ferraz-oliveira Sorry, haven't been able to work on this - and honestly, I have a little clue as anyone at this point. :(

2021-07-12 10:11 UTC, paulo-ferraz-oliveira commented
Sure. I'll close my pull request, then, since this seems to be stalled. We can reopen later if required.

2025-06-16 07:33 UTC, elbrujohalcon commented
Repo will be archived.

2025-06-16 07:33 UTC, closed without merging